server:
  host: "127.0.0.1"
  port: 8080
  publicDir: public
  thumbnailDir: thumbnail
  originalDir: original
  randomNum: 10
  token: token
  cors:
    origins: ["*"]
    methods: ["GET","POST","OPTIONS"]
    headers: ["Origin","Content-Length","Content-Type","Authorization"]
    credentials: true
watermark:
  enabled: true
  font: roboto.ttf
  text: withme.top
  pdi: 72
  size: 50
  position:
    x: 0
    y: 0
  color: 
    r: 0
    g: 0
    b: 0
    a: 255
thumbnail:
  width: 200
  height: 0
quality: 75
logFile: "log.txt"